---
title: "Bash & Tricks"
author: "Dietmar Rieder, Gregor Sturm"
output:
#  beamer_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Neat tricks

 * `cd -`: change to the previous directory
 * `realpath`: resolve all symbolic links
 * `rename`: bulk rename files 
 * `killall NAME`: kill all processes that match the name (can only kill YOUR processes)
 
 
## Loops and the like
 * `for` loop
 * `xargs`
 
If you need to use loops, consider switching straight to nextflow instead (later lecture!)

## tmux

* Terminal multiplexer

## "modern unix" programs

 * `tldr`: Drop-in replacement for `man`
 * `rga`: alternative to `grep -R`, only searches code and text files. 
 
## Monitoring the system

 * `htop` or `glances`
 * `spacereporter` (only on CePH)


## Setting up passwordless authentication for ssh

* Generate a key pair:
   - private key: stays on your computer
   - public key: put it on the server
   
Using the public key the server can check that a request comes from
your computer. 

```bash
# generate a key pair
ssh-keygen

# copy the key pair on the server
ssh-copy-id user@zeus
```



## Other resources

 * https://www.bioinformatics.babraham.ac.uk/training/Linux%20bootcamp/Linux%20Bootcamp%20Lectures.pdf


